<a href="https://colab.research.google.com/github/worldbank/dec-python-course/blob/main/1-foundations/3-numpy-and-pandas/foundations-s3-bonus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DEC Foundations of Python for Data Science - Session 3 Bonus Material

# Python Library Versioning

If you want to lock/control the versions of all packages used by your script (aka. dependencies), you can put them in a `requirements.txt` file in the format of `package_name==package_version` one package per line, then instruct pip to install the dependences in the `requirements.txt` file with bash command `pip install -r requirements.txt`. Using `requirements.txt` for dependency management is a very common practice in python projects.

## Exercises
The following exercises are meant to be completed step by step. Upon successful completion of all steps, the last cell should execute without any `AssertionError`.
1. Git clone this course repository from github: https://github.com/worldbank/dec-python-course

In [ ]:
# hint: use ! and bash command `git clone`

2. Change your working directory to the folder where this file is in `
dec-python-course/1-foundations/3-numpy-and-pandas/`

In [ ]:
# hint: use % and bash command `cd`

3. Install all python libraries as specified in `requirements.txt`, without copying the content of `requirements.txt`. Upon successful installation, click on "RESTART RUNTIME" in the code cell output.

In [ ]:
# hint: use ! and bash command `pip install` with flag `-r`

4. Import `matplotlib`'s `pyplot` module and alias it as `plt`

In [ ]:
# hint: use `import ... as ...`

# === Do not modify code below ===
fig = plt.figure(figsize=(10, 80))
assert hasattr(fig, "subfigures"),\
 "If correct version of matplotlib were installed you should not see this message"

print("Well done!")

# NumPy Extras

In [1]:
import numpy as np

two_d_array = np.array([[1, 2], [3, 4]])

## How to transpose an ndarray?

In [ ]:
two_d_array.transpose()

array([0, 1, 2, 3])

In [ ]:
# or use short T attribute on the array
two_d_array.T

array([0, 1, 2, 3])

## How to stack and split ndarrays?

Multiple arrays can be stacked together along different axes:

In [ ]:
another_two_d_array = two_d_array * 2
print(two_d_array)
print(another_two_d_array)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [ ]:
# stack row wise
vstacked = np.vstack((two_d_array, another_two_d_array))
vstacked

array([[1, 2],
       [3, 4],
       [2, 4],
       [6, 8]])

In [ ]:
# stack column wise
hstacked = np.hstack((two_d_array, another_two_d_array))
hstacked

array([[1, 2, 2, 4],
       [3, 4, 6, 8]])

An array can be split into multiple arrays, along the specified axis:

In [ ]:
vstacked

array([[1, 2],
       [3, 4],
       [2, 4],
       [6, 8]])

In [ ]:
# split to 2 arrays row wise
vsplit1, vsplit2 = np.vsplit(vstacked, 2)
print(vsplit1)
print(vsplit2)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [ ]:
# split to 2 arrays column wise
hsplit1, hsplit2 = np.hsplit(vstacked, 2)
print(hsplit1)
print(hsplit2)

[[1]
 [3]
 [2]
 [6]]
[[2]
 [4]
 [4]
 [8]]
